---
#<% require 'kitchen-sync' %>
driver:
  name: vagrant
  require_chef_omnibus: "<%= ENV['CHEF_VERSION'] || if ENV['CI'] then require 'chef/version'; Chef::VERSION else 'latest' end %>"

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[application_test]
- name: plugin
  run_list:
  - recipe[application_test::plugin]
- name: private
  run_list:
  - recipe[application_test::private]
