---
#<% require 'poise_boiler' %>
<%= PoiseBoiler.kitchen %>

suites:
- name: default
  run_list:
  - recipe[application_test]
- name: plugin
  run_list:
  - recipe[application_test::plugin]
- name: private
  run_list:
  - recipe[application_test::private]
